// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Prova1.Models;
using System;

namespace Prova1.Migrations
{
    [DbContext(typeof(Prova1Context))]
    [Migration("20190504222650_Acao")]
    partial class Acao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Prova1.Models.Acao", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Atividade")
                        .IsRequired();

                    b.Property<string>("Codigo")
                        .IsRequired();

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Acao");
                });

            modelBuilder.Entity("Prova1.Models.Compra", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Acao")
                        .IsRequired();

                    b.Property<string>("Broker")
                        .IsRequired();

                    b.Property<DateTime>("Data");

                    b.Property<int>("Quantidade");

                    b.Property<float>("Valor");

                    b.HasKey("ID");

                    b.ToTable("Compra");
                });

            modelBuilder.Entity("Prova1.Models.Info", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Data");

                    b.HasKey("ID");

                    b.ToTable("Info");
                });

            modelBuilder.Entity("Prova1.Models.Venda", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Acao")
                        .IsRequired();

                    b.Property<string>("Broker")
                        .IsRequired();

                    b.Property<DateTime>("Data");

                    b.Property<int>("Quantidade");

                    b.Property<float>("Valor");

                    b.HasKey("ID");

                    b.ToTable("Venda");
                });
#pragma warning restore 612, 618
        }
    }
}
